repos:
  - repo: local
    hooks:
      - id: docstring-linter
        name: Docstring Formatter
        entry: python lint/docstring_linter.py --check
        language: system
        files: \.py$
        types: [python]
        stages: [commit]
        pass_filenames: true
        verbose: true
      - id: generate-skill-links
        name: Generate SKILL links
        entry: python scripts/gen_skill.py
        language: python
        pass_filenames: false
        always_run: true
        verbose: true
