repos:
  - repo: local
    hooks:
      - id: docstring-linter
        name: Docstring Formatter
        entry: python lint/docstring_linter.py --check
        language: system
        files: \.py$
        types: [python]
        stages: [commit]
        pass_filenames: true
        verbose: true
