state.backend: rocksdb
state.backend.rocksdb.memory.managed: true
state.backend.rocksdb.memory.write-buffer-ratio: 0.4
state.backend.rocksdb.memory.high-prio-pool-ratio: 0.1
state.checkpoints.dir: s3://flink-checkpoints/
state.checkpoints.num-retained: 3
state.backend.rocksdb.checkpoint.transfer.thread.num: 2
state.backend.rocksdb.inccheckpoint.enabled: true
state.backend.rocksdb.timer-service.factory: ROCKSDB
state.backend.rocksdb.thread.num: 4
state.backend.rocksdb.log-level: WARN
execution.checkpointing.interval: 60s
execution.checkpointing.mode: EXACTLY_ONCE
execution.checkpointing.timeout: 300000
execution.checkpointing.min-pause: 30000
execution.checkpointing.max-concurrent-checkpoints: 1
execution.checkpointing.fail-on-checkpointing-errors: true
execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
