# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrichment.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'enrichment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nrichment.proto\x12\x13kafka.enrichment.v1\"\x8a\x01\n\x10NewsArticleEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61rticle_url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x1b\n\x13mentioned_addresses\x18\x04 \x03(\t\x12\x0c\n\x04lang\x18\x05 \x01(\t\x12\x15\n\revent_time_ms\x18\x06 \x01(\x03\"q\n\tKycUpdate\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x18\n\x10wallet_addresses\x18\x03 \x03(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\revent_time_ms\x18\x05 \x01(\x03\"}\n\x0c\x41vmScreening\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0f\n\x07verdict\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x13\n\x0bscreener_id\x18\x05 \x01(\t\x12\x15\n\revent_time_ms\x18\x06 \x01(\x03\x42\x38\n\x16io.kafka.enrichment.v1Z\x1egithub.com/kafka/enrichment/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrichment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026io.kafka.enrichment.v1Z\036github.com/kafka/enrichment/v1'
  _globals['_NEWSARTICLEEVENT']._serialized_start=42
  _globals['_NEWSARTICLEEVENT']._serialized_end=180
  _globals['_KYCUPDATE']._serialized_start=182
  _globals['_KYCUPDATE']._serialized_end=295
  _globals['_AVMSCREENING']._serialized_start=297
  _globals['_AVMSCREENING']._serialized_end=422
# @@protoc_insertion_point(module_scope)
